export const IPC = {
  auth: {
    login: 'auth:login',
    logout: 'auth:logout',
    me: 'auth:me',
    changePassword: 'auth:changePassword',
    resetPassword: 'auth:resetPassword'
  },
  users: {
    list: 'users:list',
    get: 'users:get',
    create: 'users:create',
    update: 'users:update',
    remove: 'users:remove',
    setPermissions: 'users:setPermissions',
    permissions: 'users:permissions',
    roles: 'users:roles'
  },
  clients: {
    list: 'clients:list',
    get: 'clients:get',
    create: 'clients:create',
    update: 'clients:update',
    remove: 'clients:remove',
    search: 'clients:search',
    profile: 'clients:profile',
    importPreview: 'clients:importPreview',
    importCommit: 'clients:importCommit',
    importTemplate: 'clients:importTemplate',
    addContact: 'clients:addContact',
    removeContact: 'clients:removeContact'
  },
  cases: {
    list: 'cases:list',
    get: 'cases:get',
    create: 'cases:create',
    update: 'cases:update',
    remove: 'cases:remove',
    link: 'cases:link',
    archive: 'cases:archive',
    restore: 'cases:restore',
    importPreview: 'cases:importPreview',
    importCommit: 'cases:importCommit',
    importTemplate: 'cases:importTemplate'
  },
  hearings: {
    list: 'hearings:list',
    get: 'hearings:get',
    create: 'hearings:create',
    update: 'hearings:update',
    remove: 'hearings:remove',
    postpone: 'hearings:postpone'
  },
  dashboard: { stats: 'dashboard:stats' },
  lawyers: { list: 'lawyers:list', get: 'lawyers:get', create: 'lawyers:create', update: 'lawyers:update', remove: 'lawyers:remove', reorder: 'lawyers:reorder', dashboard: 'lawyers:dashboard', savePhoto: 'lawyers:savePhoto', saveStaff: 'lawyers:saveStaff' },
  employees: { list: 'employees:list', get: 'employees:get', create: 'employees:create', update: 'employees:update', remove: 'employees:remove', attendance: 'employees:attendance', leave: 'employees:leave', staff: 'employees:staff', savePhoto: 'employees:savePhoto' },
  opponents: { list: 'opponents:list', get: 'opponents:get', create: 'opponents:create', update: 'opponents:update', remove: 'opponents:remove', linkCase: 'opponents:linkCase' },
  caseTypes: { list: 'caseTypes:list', create: 'caseTypes:create', update: 'caseTypes:update', remove: 'caseTypes:remove' },
  tasks: { list: 'tasks:list', get: 'tasks:get', create: 'tasks:create', update: 'tasks:update', remove: 'tasks:remove' },
  reminders: { list: 'reminders:list', get: 'reminders:get', create: 'reminders:create', update: 'reminders:update', remove: 'reminders:remove', dismiss: 'reminders:dismiss' },
  appointments: { list: 'appointments:list', get: 'appointments:get', create: 'appointments:create', update: 'appointments:update', remove: 'appointments:remove' },
  calendar: { events: 'calendar:events', move: 'calendar:move' },
  documents: { list: 'documents:list', get: 'documents:get', upload: 'documents:upload', update: 'documents:update', remove: 'documents:remove', open: 'documents:open', download: 'documents:download', preview: 'documents:preview', versions: 'documents:versions', rename: 'documents:rename', move: 'documents:move' },
  poa: { list: 'poa:list', get: 'poa:get', create: 'poa:create', update: 'poa:update', remove: 'poa:remove' },
  contracts: { list: 'contracts:list', get: 'contracts:get', create: 'contracts:create', update: 'contracts:update', remove: 'contracts:remove' },
  consultations: { list: 'consultations:list', create: 'consultations:create', update: 'consultations:update', remove: 'consultations:remove' },
  correspondence: { list: 'correspondence:list', create: 'correspondence:create', update: 'correspondence:update', remove: 'correspondence:remove' },
  payments: { list: 'payments:list', create: 'payments:create', remove: 'payments:remove', balance: 'payments:balance' },
  expenses: {
    list: 'expenses:list',
    create: 'expenses:create',
    remove: 'expenses:remove',
    categories: 'expenses:categories',
    staff: 'expenses:staff'
  },
  invoices: { list: 'invoices:list', get: 'invoices:get', create: 'invoices:create', update: 'invoices:update', remove: 'invoices:remove' },
  cashbox: { list: 'cashbox:list', create: 'cashbox:create', update: 'cashbox:update', transactions: 'cashbox:transactions', move: 'cashbox:move' },
  reports: { run: 'reports:run', export: 'reports:export' },
  search: { global: 'search:global', advanced: 'search:advanced', legacy: 'search:legacy' },
  lookups: { list: 'lookups:list', remember: 'lookups:remember', remove: 'lookups:remove' },
  audit: { list: 'audit:list', remove: 'audit:remove' },
  notifications: { list: 'notifications:list', read: 'notifications:read', readAll: 'notifications:readAll' },
  settings: { get: 'settings:get', set: 'settings:set', saveLogo: 'settings:saveLogo' },
  backup: { create: 'backup:create', restore: 'backup:restore', list: 'backup:list', schedule: 'backup:schedule' },
  print: { preview: 'print:preview', print: 'print:print', pdf: 'print:pdf', printers: 'print:printers', voucher: 'print:voucher', receipt: 'print:receipt', manual: 'print:manual' },
  files: { gc: 'files:gc', pick: 'files:pick', scan: 'files:scan', openUrl: 'files:openUrl' },
  updater: { check: 'updater:check', version: 'updater:version', install: 'updater:install' },
  demo: { seed: 'demo:seed', wipe: 'demo:wipe' },
  sync: { status: 'sync:status', now: 'sync:now' }
} as const

export type IpcResult<T> = { ok: true; data: T } | { ok: false; error: string; fieldErrors?: Record<string, string> }
