export const PERMISSIONS = [
  { code: 'clients.view', nameAr: 'مشاهدة الموكلين', nameEn: 'View clients', module: 'clients' },
  { code: 'clients.create', nameAr: 'إضافة موكل', nameEn: 'Create client', module: 'clients' },
  { code: 'clients.update', nameAr: 'تعديل موكل', nameEn: 'Update client', module: 'clients' },
  { code: 'clients.delete', nameAr: 'حذف موكل', nameEn: 'Delete client', module: 'clients' },
  { code: 'clients.unmask_contact', nameAr: 'إظهار هاتف وإيميل الموكل', nameEn: 'Unmask client contact', module: 'clients' },
  { code: 'cases.view', nameAr: 'مشاهدة القضايا', nameEn: 'View cases', module: 'cases' },
  { code: 'cases.create', nameAr: 'إضافة قضية', nameEn: 'Create case', module: 'cases' },
  { code: 'cases.update', nameAr: 'تعديل قضية', nameEn: 'Update case', module: 'cases' },
  { code: 'cases.delete', nameAr: 'حذف قضية', nameEn: 'Delete case', module: 'cases' },
  { code: 'hearings.view', nameAr: 'مشاهدة الجلسات', nameEn: 'View hearings', module: 'hearings' },
  { code: 'hearings.create', nameAr: 'إضافة جلسة', nameEn: 'Create hearing', module: 'hearings' },
  { code: 'hearings.update', nameAr: 'تعديل جلسة', nameEn: 'Update hearing', module: 'hearings' },
  { code: 'hearings.delete', nameAr: 'حذف جلسة', nameEn: 'Delete hearing', module: 'hearings' },
  { code: 'documents.view', nameAr: 'مشاهدة المستندات', nameEn: 'View documents', module: 'documents' },
  { code: 'documents.upload', nameAr: 'رفع مستندات', nameEn: 'Upload documents', module: 'documents' },
  { code: 'documents.delete', nameAr: 'حذف مستندات', nameEn: 'Delete documents', module: 'documents' },
  { code: 'accounts.view', nameAr: 'مشاهدة الحسابات', nameEn: 'View accounts', module: 'accounts' },
  { code: 'accounts.expense', nameAr: 'إضافة مصروف', nameEn: 'Add expense', module: 'accounts' },
  { code: 'accounts.payment', nameAr: 'إضافة دفعة', nameEn: 'Add payment', module: 'accounts' },
  { code: 'reports.view', nameAr: 'مشاهدة التقارير', nameEn: 'View reports', module: 'reports' },
  { code: 'users.manage', nameAr: 'إدارة المستخدمين', nameEn: 'Manage users', module: 'users' },
  { code: 'settings.manage', nameAr: 'إدارة الإعدادات', nameEn: 'Manage settings', module: 'settings' },
  { code: 'calendar.view', nameAr: 'مشاهدة التقويم', nameEn: 'View calendar', module: 'calendar' },
  { code: 'tasks.view', nameAr: 'مشاهدة المهام', nameEn: 'View tasks', module: 'tasks' },
  { code: 'tasks.manage', nameAr: 'إدارة المهام', nameEn: 'Manage tasks', module: 'tasks' },
  { code: 'reminders.view', nameAr: 'مشاهدة التذكيرات', nameEn: 'View reminders', module: 'reminders' },
  { code: 'poa.view', nameAr: 'مشاهدة التوكيلات', nameEn: 'View power of attorney', module: 'poa' },
  { code: 'poa.manage', nameAr: 'إدارة التوكيلات', nameEn: 'Manage power of attorney', module: 'poa' },
  { code: 'contracts.view', nameAr: 'مشاهدة العقود', nameEn: 'View contracts', module: 'contracts' },
  { code: 'contracts.manage', nameAr: 'إدارة العقود', nameEn: 'Manage contracts', module: 'contracts' },
  { code: 'opponents.view', nameAr: 'مشاهدة الخصوم', nameEn: 'View opponents', module: 'opponents' },
  { code: 'opponents.manage', nameAr: 'إدارة الخصوم', nameEn: 'Manage opponents', module: 'opponents' },
  { code: 'lawyers.view', nameAr: 'مشاهدة المحامين', nameEn: 'View lawyers', module: 'lawyers' },
  { code: 'employees.view', nameAr: 'مشاهدة الموظفين', nameEn: 'View employees', module: 'employees' },
  { code: 'employees.manage', nameAr: 'إدارة الموظفين', nameEn: 'Manage employees', module: 'employees' },
  { code: 'consultations.view', nameAr: 'مشاهدة الاستشارات', nameEn: 'View consultations', module: 'consultations' },
  { code: 'consultations.manage', nameAr: 'إدارة الاستشارات', nameEn: 'Manage consultations', module: 'consultations' },
  { code: 'correspondence.view', nameAr: 'مشاهدة المراسلات', nameEn: 'View correspondence', module: 'correspondence' },
  { code: 'correspondence.manage', nameAr: 'إدارة المراسلات', nameEn: 'Manage correspondence', module: 'correspondence' },
  { code: 'cashbox.view', nameAr: 'مشاهدة الخزينة', nameEn: 'View cashbox', module: 'cashbox' },
  { code: 'invoices.view', nameAr: 'مشاهدة الفواتير', nameEn: 'View invoices', module: 'invoices' },
  { code: 'invoices.manage', nameAr: 'إدارة الفواتير', nameEn: 'Manage invoices', module: 'invoices' },
  { code: 'archive.view', nameAr: 'مشاهدة الأرشيف', nameEn: 'View archive', module: 'archive' },
  { code: 'audit.view', nameAr: 'مشاهدة سجل العمليات', nameEn: 'View audit log', module: 'audit' },
  { code: 'audit.delete', nameAr: 'حذف سجل العمليات', nameEn: 'Delete audit log', module: 'audit' },
  { code: 'backup.manage', nameAr: 'إدارة النسخ الاحتياطي', nameEn: 'Manage backup', module: 'backup' },
  { code: 'appointments.view', nameAr: 'مشاهدة المواعيد', nameEn: 'View appointments', module: 'appointments' },
  { code: 'appointments.manage', nameAr: 'إدارة المواعيد', nameEn: 'Manage appointments', module: 'appointments' }
] as const

export function shouldMaskClientContact(roleCode?: string, permissions: string[] = []): boolean {
  if (!roleCode) return false
  if (roleCode === 'admin') return false
  return !permissions.includes('clients.unmask_contact')
}

export type PermissionCode = (typeof PERMISSIONS)[number]['code']

export const ROLES = [
  { code: 'admin', nameAr: 'المدير', nameEn: 'Admin' },
  { code: 'lawyer', nameAr: 'المحامي', nameEn: 'Lawyer' },
  { code: 'legal_assistant', nameAr: 'مساعد المحامي', nameEn: 'Legal Assistant' },
  { code: 'secretary', nameAr: 'الموظف الإداري', nameEn: 'Secretary' },
  { code: 'accountant', nameAr: 'المحاسب', nameEn: 'Accountant' },
  { code: 'custom', nameAr: 'مستخدم مخصص', nameEn: 'Custom User' }
] as const

export const ROLE_PERMISSIONS: Record<string, PermissionCode[]> = {
  admin: PERMISSIONS.map((p) => p.code),
  lawyer: [
    'clients.view',
    'clients.create',
    'clients.update',
    'clients.unmask_contact',
    'cases.view',
    'cases.create',
    'cases.update',
    'hearings.view',
    'hearings.create',
    'hearings.update',
    'documents.view',
    'documents.upload',
    'calendar.view',
    'tasks.view',
    'tasks.manage',
    'reminders.view',
    'poa.view',
    'poa.manage',
    'contracts.view',
    'contracts.manage',
    'opponents.view',
    'opponents.manage',
    'lawyers.view',
    'consultations.view',
    'consultations.manage',
    'correspondence.view',
    'appointments.view',
    'appointments.manage',
    'archive.view'
  ],
  legal_assistant: [
    'clients.view',
    'clients.create',
    'clients.update',
    'cases.view',
    'cases.update',
    'hearings.view',
    'hearings.create',
    'hearings.update',
    'documents.view',
    'documents.upload',
    'calendar.view',
    'tasks.view',
    'tasks.manage',
    'reminders.view',
    'poa.view',
    'contracts.view',
    'opponents.view',
    'consultations.view',
    'correspondence.view',
    'correspondence.manage',
    'appointments.view',
    'appointments.manage'
  ],
  secretary: [
    'clients.view',
    'clients.create',
    'clients.update',
    'cases.view',
    'hearings.view',
    'documents.view',
    'calendar.view',
    'tasks.view',
    'reminders.view',
    'appointments.view',
    'appointments.manage',
    'correspondence.view',
    'correspondence.manage'
  ],
  accountant: [
    'clients.view',
    'cases.view',
    'accounts.view',
    'accounts.expense',
    'accounts.payment',
    'reports.view',
    'cashbox.view',
    'invoices.view',
    'invoices.manage'
  ],
  custom: []
}

export function canAccessPage(page: string, roleCode: string, permissions: string[]): boolean {
  if (roleCode === 'admin') return true
  const need = PAGE_ACCESS[page]
  if (need === undefined) return false
  if (Array.isArray(need) && need.length === 0) return true
  const list = Array.isArray(need) ? need : [need]
  return list.some((code) => permissions.includes(code))
}

export const PAGE_ACCESS: Record<string, PermissionCode | PermissionCode[] | []> = {
  home: [],
  dashboard: [],
  clients: 'clients.view',
  clientProfile: 'clients.view',
  cases: 'cases.view',
  caseProfile: 'cases.view',
  hearings: 'hearings.view',
  calendar: 'calendar.view',
  tasks: 'tasks.view',
  reminders: 'reminders.view',
  documents: 'documents.view',
  poa: 'poa.view',
  contracts: 'contracts.view',
  opponents: 'opponents.view',
  opponentProfile: 'opponents.view',
  lawyers: 'lawyers.view',
  lawyerProfile: 'lawyers.view',
  employees: 'employees.view',
  employeeProfile: 'employees.view',
  staffForm: ['users.manage', 'employees.manage', 'lawyers.view', 'employees.view'],
  consultations: 'consultations.view',
  correspondence: 'correspondence.view',
  accounts: 'accounts.view',
  cashbox: 'cashbox.view',
  expenses: ['accounts.view', 'accounts.expense'],
  invoices: 'invoices.view',
  reports: 'reports.view',
  archive: 'archive.view',
  users: 'users.manage',
  audit: 'audit.view',
  settings: ['settings.manage', 'backup.manage'],
  appointments: 'appointments.view',
  search: 'cases.view'
}

export const NAV_ITEMS: { id: string; permission?: PermissionCode; icon?: string }[] = [
  { id: 'home' },
  { id: 'dashboard' },
  { id: 'clients', permission: 'clients.view' },
  { id: 'cases', permission: 'cases.view' },
  { id: 'hearings', permission: 'hearings.view' },
  { id: 'calendar', permission: 'calendar.view' },
  { id: 'appointments', permission: 'appointments.view' },
  { id: 'tasks', permission: 'tasks.view' },
  { id: 'reminders', permission: 'reminders.view' },
  { id: 'documents', permission: 'documents.view' },
  { id: 'poa', permission: 'poa.view' },
  { id: 'contracts', permission: 'contracts.view' },
  { id: 'opponents', permission: 'opponents.view' },
  { id: 'lawyers', permission: 'lawyers.view' },
  { id: 'employees', permission: 'employees.view' },
  { id: 'consultations', permission: 'consultations.view' },
  { id: 'correspondence', permission: 'correspondence.view' },
  { id: 'accounts', permission: 'accounts.view' },
  { id: 'cashbox', permission: 'cashbox.view' },
  { id: 'expenses', permission: 'accounts.expense' },
  { id: 'invoices', permission: 'invoices.view' },
  { id: 'reports', permission: 'reports.view' },
  { id: 'archive', permission: 'archive.view' },
  { id: 'users', permission: 'users.manage' },
  { id: 'audit', permission: 'audit.view' },
  { id: 'settings', permission: 'settings.manage' }
]
